"""Local proposal-only inference package for BarunAction-35M."""

from .candidate import (
    BASE_MODEL_NAME,
    CANDIDATE_ARM_ID,
    CANDIDATE_CHECKPOINT_SHA256,
    CANDIDATE_ID,
    CANDIDATE_MANIFEST_SHA256,
    CANDIDATE_RELATIVE_CHECKPOINT_PATH,
    CANDIDATE_RUN_ID,
    CANDIDATE_SELECTION_RUN_ID,
    CANDIDATE_STEP,
    MODEL_NAME,
    candidate_identity,
)
from .inference import (
    DEFAULT_MAX_NEW_TOKENS,
    PROMPT_CONTRACT_VERSION,
    RESULT_SCHEMA_VERSION,
    BarunActionCompiler,
    ErrorDetail,
    InferenceOutcome,
    PolicyAssessment,
    assess_policy,
    render_prompt,
    validate_action_output,
)
from .quantization import (
    INT8_SMOKE_CASES_VERSION,
    INT8_SMOKE_REPORT_VERSION,
    ActionIRSmokeCase,
    QuantizationSmokeError,
    compare_int8_action_ir,
    parse_int8_smoke_cases,
)
from .schema import (
    SCHEMA_CONTRACT_VERSION,
    ContractError,
    PreparedInput,
    ToolDeclaration,
    canonical_context,
    canonical_now,
    parse_tool_declarations,
    prepare_input,
)
from .simulator import (
    SIMULATOR_SCHEMA_VERSION,
    SimulationResult,
    simulate_action,
)

__all__ = [
    "BASE_MODEL_NAME",
    "CANDIDATE_ARM_ID",
    "CANDIDATE_CHECKPOINT_SHA256",
    "CANDIDATE_ID",
    "CANDIDATE_MANIFEST_SHA256",
    "CANDIDATE_RELATIVE_CHECKPOINT_PATH",
    "CANDIDATE_RUN_ID",
    "CANDIDATE_SELECTION_RUN_ID",
    "CANDIDATE_STEP",
    "DEFAULT_MAX_NEW_TOKENS",
    "INT8_SMOKE_CASES_VERSION",
    "INT8_SMOKE_REPORT_VERSION",
    "MODEL_NAME",
    "PROMPT_CONTRACT_VERSION",
    "RESULT_SCHEMA_VERSION",
    "SCHEMA_CONTRACT_VERSION",
    "SIMULATOR_SCHEMA_VERSION",
    "ActionIRSmokeCase",
    "BarunActionCompiler",
    "ContractError",
    "ErrorDetail",
    "InferenceOutcome",
    "PolicyAssessment",
    "PreparedInput",
    "QuantizationSmokeError",
    "SimulationResult",
    "ToolDeclaration",
    "assess_policy",
    "candidate_identity",
    "canonical_context",
    "canonical_now",
    "compare_int8_action_ir",
    "parse_int8_smoke_cases",
    "parse_tool_declarations",
    "prepare_input",
    "render_prompt",
    "simulate_action",
    "validate_action_output",
]
